kind: pipeline
type: kubernetes
name: default

services:
- name: postgres
  image: postgres:latest
  environment:
    POSTGRES_HOST_AUTH_METHOD: trust
    POSTGRES_USER: root
    POSTGRES_DB: root
  resources:
    requests:
      cpu: 2000
      memory: 2Gi    
  ports:
  - name: postgres
    port: 5432

- name: redis
  image: redis:3.0
  ports:
  - name: redis
    port: 6379
  resources:
    requests:
      cpu: 50
      memory: 10MiB    

steps:
- name: test
  image: python:2.7.18-stretch
  commands:
    - pip install tox
    - tox -e py27-postgresql
  resources:
    requests:
      cpu: 2000
      memory: 2Gi      
  environment:
    PG_HOST: postgres
    PG_USER: root
    POSTGRESQL_URI: postgresql://root@postgres:5432/
    REDIS_HOST: redis
    REDIS_PORT: "6379"
