kind: pipeline
type: kubernetes
name: default

services:
- name: postgres
  image: postgres:latest
  environment:
    POSTGRES_HOST_AUTH_METHOD: trust
    POSTGRES_USER: root
    POSTGRES_DB: root
  ports:
  - name: postgres
    port: 5432

- name: redis
  image: redis:3.0
  ports:
  - name: redis
    port: 6379

steps:
- name: test
  image: python:3.7.1-stretch
  commands:
    - pip install tox
    - tox -e py37-postgresql
  environment:
    PG_HOST: postgres
    PG_USER: root
    POSTGRESQL_URI: postgresql://root@postgres:5432/
    REDIS_HOST: redis
    REDIS_PORT: "6379"
